# Generated by Django 5.0.1 on 2024-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=50)),
            ],
        ),
    ]
