# Generated by Django 5.0.1 on 2024-12-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaApp', '0002_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ADD_PRODUCT', 'Agregar Producto'), ('ADD_PROVIDER', 'Agregar Proveedor')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
