# Generated by Django 5.0.1 on 2024-12-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodegaApp', '0003_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('ADD_PRODUCT', 'Agregar Producto'), ('ADD_PROVIDER', 'Agregar Proveedor'), ('DELETE_PRODUCT', 'Eliminar Producto'), ('DELETE_PROVIDER', 'Eliminar Proveedor'), ('EDIT_PRODUCT', 'Editar Producto'), ('EDIT_PROVIDER', 'Editar Proveedor')], max_length=20),
        ),
    ]
